name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        ls
        pip install pyyaml beautifulsoup4 markdown jinja2

    - name: Run Python script
      run: |
        python scripts/main.py

    - name: Configure Git
      run: |
        git config --global user.name "EmeraldThunder1"
        git config --global user.email "github@dapoole.co.uk"
    - name: Create deployment branch
      run: |
        git checkout -b deployment
    - name: Stage changes
      run: |
        git add *
        git commit -m "Automated build"
    - name: Pull latest changes
      run: |
        git pull origin deployment --rebase

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PUSH_TOKEN }}
        branch: deployment
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PUSH_TOKEN }}
        publish_dir: ./build
        branch: deployment